# Great Expectations Basics

This example will walk through using basic expectations with crop data from the Food and Agricultural Organization of the United States.

Data are available here: http://www.fao.org/faostat/en/#home

In [1]:
import pandas as pd

import great_expectations as gx

In [3]:
df = pd.read_csv("../data/FAO-Rice-Production-Asia.csv")

## Exploratory Data Analysis

We typically will need to investigate some properites of our data to understand what we can do with it. Jupyter makes that easy, and we will take advantage of its features, including autocomplete, extensively.

In [4]:
df.head()

,Domain Code,Domain,Area Code,Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value,Flag,Flag Description
0,QC,Crops,2,Afghanistan,5419,Yield,27,"Rice, paddy",1961,1961,hg/ha,15190,Fc,Calculated data
1,QC,Crops,2,Afghanistan,5419,Yield,27,"Rice, paddy",1962,1962,hg/ha,15190,Fc,Calculated data
2,QC,Crops,2,Afghanistan,5419,Yield,27,"Rice, paddy",1963,1963,hg/ha,15190,Fc,Calculated data
3,QC,Crops,2,Afghanistan,5419,Yield,27,"Rice, paddy",1964,1964,hg/ha,17273,Fc,Calculated data
4,QC,Crops,2,Afghanistan,5419,Yield,27,"Rice, paddy",1965,1965,hg/ha,17273,Fc,Calculated data

### Reshape data

In [5]:
pivoted = df.pivot(index="Year", columns="Area", values="Value")

In [6]:
pivoted.head()

Area,Afghanistan,Azerbaijan,Bangladesh,Bhutan,Brunei Darussalam,Cambodia,"China, Hong Kong SAR","China, Taiwan Province of","China, mainland",Democratic People's Republic of Korea,...,Saudi Arabia,Sri Lanka,Syrian Arab Republic,Tajikistan,Thailand,Timor-Leste,Turkey,Turkmenistan,Uzbekistan,Viet Nam
Year,,,,,,,,,,,,,,,,,,,,,
1961,15190.0,NaN,17005.0,20000.0,17306.0,10921.0,20168.0,32663.0,20434.0,43071.0,...,28000.0,18626.0,25000.0,NaN,16585.0,19949.0,39542.0,NaN,NaN,18966.0
1962,15190.0,NaN,15302.0,20000.0,18527.0,8920.0,17201.0,33723.0,23408.0,43116.0,...,26500.0,19539.0,26100.0,NaN,17202.0,17000.0,33951.0,NaN,NaN,19937.0
1963,15190.0,NaN,17690.0,20000.0,13711.0,11742.0,18408.0,33583.0,26642.0,46056.0,...,28492.0,19547.0,24473.0,NaN,18725.0,15385.0,39400.0,NaN,NaN,21400.0
1964,17273.0,NaN,17070.0,20000.0,13235.0,11611.0,13962.0,37244.0,28062.0,45335.0,...,25000.0,19962.0,20000.0,NaN,18384.0,13652.0,47629.0,NaN,NaN,19441.0
1965,17273.0,NaN,16827.0,20000.0,11737.0,10666.0,24362.0,38454.0,29441.0,39688.0,...,23333.0,17696.0,19091.0,NaN,17805.0,16599.0,43340.0,NaN,NaN,19414.0

### Initialize the new dataset to work with Great Expectations

In [8]:
df = gx.from_pandas(pivoted)

In [9]:
df.expect_column_mean_to_be_between("Afghanistan", 15000, 25000)

{
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "result": {
    "observed_value": 21998.314814814814,
    "element_count": 54,
    "missing_count": null,
    "missing_percent": null
  },
  "success": true,
  "meta": {}
}

In [10]:
### We might want to make expectations about lots of columns

In [11]:
for column in df.columns:
    # print('Column: ' + column + "\nResult: " + str(df.expect_column_mean_to_be_between(column, 15000, 25000)))
    result = df.expect_column_mean_to_be_between(column, 15000, 25000)
    if result["success"] == False:
        print(column)
        print(result)

Azerbaijan
{
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "result": {
    "observed_value": 31669.82608695652,
    "element_count": 54,
    "missing_count": 31,
    "missing_percent": 57.407407407407405
  },
  "success": false,
  "meta": {},
  "expectation_config": {
    "expectation_type": "expect_column_mean_to_be_between",
    "kwargs": {
      "column": "Azerbaijan",
      "min_value": 15000,
      "max_value": 25000,
      "result_format": "BASIC"
    },
    "meta": {}
  }
}
Bangladesh
{
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "result": {
    "observed_value": 26318.537037037036,
    "element_count": 54,
    "missing_count": null,
    "missing_percent": null
  },
  "success": false,
  "meta": {},
  "expectation_config": {
    "expectation_type": "expect_column_mean_to_be_between",
    "kwargs": {
      "column": "Bangladesh",
      "min_value": 15000,
      "max_value": 25000,
      "result_format": "BASIC"
    },
    "meta": {}
  }
}
Brunei Darussalam
{
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "result": {
    "observed_value": 14196.796296296296,
    "element_count": 54,
    "missing_count": null,
    "missing_percent": null
  },
  "success": false,
  "meta": {},
  "expectation_config": {
    "expectation_type": "expect_column_mean_to_be_between",
    "kwargs": {
      "column": "Brunei Darussalam",
      "min_value": 15000,
      "max_value": 25000,
      "result_format": "BASIC"
    },
    "meta": {}
  }
}
China, Taiwan Province of
{
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "result": {
    "observed_value": 49080.055555555555,
    "element_count": 54,
    "missing_count": null,
    "missing_percent": null
  },
  "success": false,
  "meta": {},
  "expectation_config": {
    "expectation_type": "expect_column_mean_to_be_between",
    "kwargs": {
      "column": "China, Taiwan Province of",
      "min_value": 15000,
      "max_value": 25000,
      "result_format": "BASIC"
    },
    "meta": {}
  }
}
China, mainland
{
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "result": {
    "observed_value": 49688.81481481482,
    "element_count": 54,
    "missing_count": null,
    "missing_percent": null
  },
  "success": false,
  "meta": {},
  "expectation_config": {
    "expectation_type": "expect_column_mean_to_be_between",
    "kwargs": {
      "column": "China, mainland",
      "min_value": 15000,
      "max_value": 25000,
      "result_format": "BASIC"
    },
    "meta": {}
  }
}
Democratic People's Republic of Korea
{
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "result": {
    "observed_value": 42581.22222222222,
    "element_count": 54,
    "missing_count": null,
    "missing_percent": null
  },
  "success": false,
  "meta": {},
  "expectation_config": {
    "expectation_type": "expect_column_mean_to_be_between",
    "kwargs": {
      "column": "Democratic People's Republic of Korea",
      "min_value": 15000,
      "max_value": 25000,
      "result_format": "BASIC"
    },
    "meta": {}
  }
}
Indonesia
{
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "result": {
    "observed_value": 36438.2037037037,
    "element_count": 54,
    "missing_count": null,
    "missing_percent": null
  },
  "success": false,
  "meta": {},
  "expectation_config": {
    "expectation_type": "expect_column_mean_to_be_between",
    "kwargs": {
      "column": "Indonesia",
      "min_value": 15000,
      "max_value": 25000,
      "result_format": "BASIC"
    },
    "meta": {}
  }
}
Iran (Islamic Republic of)
{
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "result": {
    "observed_value": 35963.87037037037,
    "element_count": 54,
    "missing_count": null,
    "missing_percent": null
  },
  "success": false,
  "meta": {},
  "expectation_config": {
    "expectation_type": "expect_column_mean_to_be_between",
    "kwargs": {
      "column": "Iran (Islamic Republic of)",
      "min_value": 15000,
      "max_value": 25000,
      "result_format": "BASIC"
    },
    "meta": {}
  }
}
Iraq
{
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "result": {
    "observed_value": 27489.62962962963,
    "element_count": 54,
    "missing_count": null,
    "missing_percent": null
  },
  "success": false,
  "meta": {},
  "expectation_config": {
    "expectation_type": "expect_column_mean_to_be_between",
    "kwargs": {
      "column": "Iraq",
      "min_value": 15000,
      "max_value": 25000,
      "result_format": "BASIC"
    },
    "meta": {}
  }
}
Japan
{
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "result": {
    "observed_value": 60217.46296296296,
    "element_count": 54,
    "missing_count": null,
    "missing_percent": null
  },
  "success": false,
  "meta": {},
  "expectation_config": {
    "expectation_type": "expect_column_mean_to_be_between",
    "kwargs": {
      "column": "Japan",
      "min_value": 15000,
      "max_value": 25000,
      "result_format": "BASIC"
    },
    "meta": {}
  }
}
Kazakhstan
{
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "result": {
    "observed_value": 33158.608695652176,
    "element_count": 54,
    "missing_count": 31,
    "missing_percent": 57.407407407407405
  },
  "success": false,
  "meta": {},
  "expectation_config": {
    "expectation_type": "expect_column_mean_to_be_between",
    "kwargs": {
      "column": "Kazakhstan",
      "min_value": 15000,
      "max_value": 25000,
      "result_format": "BASIC"
    },
    "meta": {}
  }
}
Kyrgyzstan
{
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "result": {
    "observed_value": 26061.82608695652,
    "element_count": 54,
    "missing_count": 31,
    "missing_percent": 57.407407407407405
  },
  "success": false,
  "meta": {},
  "expectation_config": {
    "expectation_type": "expect_column_mean_to_be_between",
    "kwargs": {
      "column": "Kyrgyzstan",
      "min_value": 15000,
      "max_value": 25000,
      "result_format": "BASIC"
    },
    "meta": {}
  }
}
Malaysia
{
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "result": {
    "observed_value": 28591.11111111111,
    "element_count": 54,
    "missing_count": null,
    "missing_percent": null
  },
  "success": false,
  "meta": {},
  "expectation_config": {
    "expectation_type": "expect_column_mean_to_be_between",
    "kwargs": {
      "column": "Malaysia",
      "min_value": 15000,
      "max_value": 25000,
      "result_format": "BASIC"
    },
    "meta": {}
  }
}
Myanmar
{
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "result": {
    "observed_value": 27868.09259259259,
    "element_count": 54,
    "missing_count": null,
    "missing_percent": null
  },
  "success": false,
  "meta": {},
  "expectation_config": {
    "expectation_type": "expect_column_mean_to_be_between",
    "kwargs": {
      "column": "Myanmar",
      "min_value": 15000,
      "max_value": 25000,
      "result_format": "BASIC"
    },
    "meta": {}
  }
}
Philippines
{
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "result": {
    "observed_value": 25413.88888888889,
    "element_count": 54,
    "missing_count": null,
    "missing_percent": null
  },
  "success": false,
  "meta": {},
  "expectation_config": {
    "expectation_type": "expect_column_mean_to_be_between",
    "kwargs": {
      "column": "Philippines",
      "min_value": 15000,
      "max_value": 25000,
      "result_format": "BASIC"
    },
    "meta": {}
  }
}
Republic of Korea
{
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "result": {
    "observed_value": 58515.833333333336,
    "element_count": 54,
    "missing_count": null,
    "missing_percent": null
  },
  "success": false,
  "meta": {},
  "expectation_config": {
    "expectation_type": "expect_column_mean_to_be_between",
    "kwargs": {
      "column": "Republic of Korea",
      "min_value": 15000,
      "max_value": 25000,
      "result_format": "BASIC"
    },
    "meta": {}
  }
}
Sri Lanka
{
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "result": {
    "observed_value": 28791.944444444445,
    "element_count": 54,
    "missing_count": null,
    "missing_percent": null
  },
  "success": false,
  "meta": {},
  "expectation_config": {
    "expectation_type": "expect_column_mean_to_be_between",
    "kwargs": {
      "column": "Sri Lanka",
      "min_value": 15000,
      "max_value": 25000,
      "result_format": "BASIC"
    },
    "meta": {}
  }
}
Syrian Arab Republic
{
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "result": {
    "observed_value": 41519.61111111111,
    "element_count": 54,
    "missing_count": 18,
    "missing_percent": 33.333333333333336
  },
  "success": false,
  "meta": {},
  "expectation_config": {
    "expectation_type": "expect_column_mean_to_be_between",
    "kwargs": {
      "column": "Syrian Arab Republic",
      "min_value": 15000,
      "max_value": 25000,
      "result_format": "BASIC"
    },
    "meta": {}
  }
}
Tajikistan
{
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "result": {
    "observed_value": 36140.34782608696,
    "element_count": 54,
    "missing_count": 31,
    "missing_percent": 57.407407407407405
  },
  "success": false,
  "meta": {},
  "expectation_config": {
    "expectation_type": "expect_column_mean_to_be_between",
    "kwargs": {
      "column": "Tajikistan",
      "min_value": 15000,
      "max_value": 25000,
      "result_format": "BASIC"
    },
    "meta": {}
  }
}
Turkey
{
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "result": {
    "observed_value": 52992.22222222222,
    "element_count": 54,
    "missing_count": null,
    "missing_percent": null
  },
  "success": false,
  "meta": {},
  "expectation_config": {
    "expectation_type": "expect_column_mean_to_be_between",
    "kwargs": {
      "column": "Turkey",
      "min_value": 15000,
      "max_value": 25000,
      "result_format": "BASIC"
    },
    "meta": {}
  }
}
Uzbekistan
{
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "result": {
    "observed_value": 35319.217391304344,
    "element_count": 54,
    "missing_count": 31,
    "missing_percent": 57.407407407407405
  },
  "success": false,
  "meta": {},
  "expectation_config": {
    "expectation_type": "expect_column_mean_to_be_between",
    "kwargs": {
      "column": "Uzbekistan",
      "min_value": 15000,
      "max_value": 25000,
      "result_format": "BASIC"
    },
    "meta": {}
  }
}
Viet Nam
{
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "result": {
    "observed_value": 32705.203703703704,
    "element_count": 54,
    "missing_count": null,
    "missing_percent": null
  },
  "success": false,
  "meta": {},
  "expectation_config": {
    "expectation_type": "expect_column_mean_to_be_between",
    "kwargs": {
      "column": "Viet Nam",
      "min_value": 15000,
      "max_value": 25000,
      "result_format": "BASIC"
    },
    "meta": {}
  }
}

### Now, we can view and save the expectations that we have created

In [14]:
print(df.get_expectation_suite())

{
  "data_asset_type": "Dataset",
  "expectation_suite_name": "default",
  "expectations": [
    {
      "expectation_type": "expect_column_mean_to_be_between",
      "kwargs": {
        "column": "Afghanistan",
        "min_value": 15000,
        "max_value": 25000
      },
      "meta": {}
    },
    {
      "expectation_type": "expect_column_mean_to_be_between",
      "kwargs": {
        "column": "Bhutan",
        "min_value": 15000,
        "max_value": 25000
      },
      "meta": {}
    },
    {
      "expectation_type": "expect_column_mean_to_be_between",
      "kwargs": {
        "column": "Cambodia",
        "min_value": 15000,
        "max_value": 25000
      },
      "meta": {}
    },
    {
      "expectation_type": "expect_column_mean_to_be_between",
      "kwargs": {
        "column": "China, Hong Kong SAR",
        "min_value": 15000,
        "max_value": 25000
      },
      "meta": {}
    },
    {
      "expectation_type": "expect_column_mean_to_be_between",
      "kwargs": {
        "column": "India",
        "min_value": 15000,
        "max_value": 25000
      },
      "meta": {}
    },
    {
      "expectation_type": "expect_column_mean_to_be_between",
      "kwargs": {
        "column": "Lao People's Democratic Republic",
        "min_value": 15000,
        "max_value": 25000
      },
      "meta": {}
    },
    {
      "expectation_type": "expect_column_mean_to_be_between",
      "kwargs": {
        "column": "Nepal",
        "min_value": 15000,
        "max_value": 25000
      },
      "meta": {}
    },
    {
      "expectation_type": "expect_column_mean_to_be_between",
      "kwargs": {
        "column": "Pakistan",
        "min_value": 15000,
        "max_value": 25000
      },
      "meta": {}
    },
    {
      "expectation_type": "expect_column_mean_to_be_between",
      "kwargs": {
        "column": "Saudi Arabia",
        "min_value": 15000,
        "max_value": 25000
      },
      "meta": {}
    },
    {
      "expectation_type": "expect_column_mean_to_be_between",
      "kwargs": {
        "column": "Thailand",
        "min_value": 15000,
        "max_value": 25000
      },
      "meta": {}
    },
    {
      "expectation_type": "expect_column_mean_to_be_between",
      "kwargs": {
        "column": "Timor-Leste",
        "min_value": 15000,
        "max_value": 25000
      },
      "meta": {}
    },
    {
      "expectation_type": "expect_column_mean_to_be_between",
      "kwargs": {
        "column": "Turkmenistan",
        "min_value": 15000,
        "max_value": 25000
      },
      "meta": {}
    }
  ],
  "ge_cloud_id": null,
  "meta": {
    "great_expectations_version": "0.14.10"
  }
}